apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80        # Port you will access
      targetPort: 8080 # Laravel container port
  type: NodePort
