---
- name: Laravel Kubernetes Deployment Test (Skip npm)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    web_pod_label: "app=laravel-app"
    laravel_path: "/var/www/html"

  tasks:
    - name: Get the name of the web server pod
      shell: kubectl get pods -l app=laravel-app -o jsonpath="{.items[0].metadata.name}"
      register: web_pod


    - name: Show web pod name
      debug:
        msg: "Web pod is {{ web_pod.stdout }}"

    - name: Mark Laravel directory as safe for Git
      shell: kubectl exec {{ web_pod.stdout }} -c laravel-web -- git config --global --add safe.directory {{ laravel_path }}

    - name: Set upstream branch for master
      shell: kubectl exec {{ web_pod.stdout }} -c laravel-web -- bash -c "cd {{ laravel_path }} && git branch --set-upstream-to=origin/master master"

    - name: Clean untracked files so git pull works
      shell: kubectl exec {{ web_pod.stdout }} -c laravel-web -- bash -c "cd {{ laravel_path }} && git clean -fd"

    - name: Git pull latest code
      shell: kubectl exec {{ web_pod.stdout }} -c laravel-web -- bash -c "cd {{ laravel_path }} && git pull"

    - name: Install PHP dependencies with Composer
      shell: kubectl exec {{ web_pod.stdout }} -c laravel-web -- bash -c "cd {{ laravel_path }} && composer install --no-interaction --prefer-dist"

    